-- select ASMENS_KODAS, VARDAS, PAVARDĖ 
-- from DARBUOTOJAS
-- WHERE ASMENS_KODAS LIKE "_880720%";
-- SELECT DIRBA_NUO, ASMENS_KODAS from DARBUOTOJAS
-- WHERE DIRBA_NUO > "2009-10-30" AND DIRBA_NUO < "2012-12-11";
-- SELECT VARDAS, SKYRIUS_ID, PROJEKTAS_ID FROM DARBUOTOJAS
-- where SKYRIUS_ID IN (2,3);
-- SELECT VARDAS, PAVARDĖ, ASMENS_KODAS from DARBUOTOJAS
-- WHERE ASMENS_KODAS LIKE "4%" or ASMENS_KODAS LIKE "6%";
-- SELECT * FROM DARBUOTOJAS
-- WHERE ASMENS_KODAS LIKE "_____12%";
-- SELECT pavadinimas as PROJEKTAS from PROJEKTAS
-- WHERE PAVADINIMAS like "_a%";
-- select * FROM DARBUOTOJAS
-- where PAREIGOS is null;
-- SELECT VARDAS, PAVARDĖ, DIRBA_NUO, PAREIGOS from DARBUOTOJAS
-- where DIRBA_NUO > "2011-01-12" and PAREIGOS="Programuotojas";
-- SELECT VARDAS, PAVARDĖ, SKYRIUS_ID, PROJEKTAS_ID from DARBUOTOJAS
-- WHERE SKYRIUS_ID=2 or PROJEKTAS_ID=1;
-- select VARDAS from DARBUOTOJAS
-- where VARDAS not LIKE "A%";
-- SELECT VARDAS, PAVARDĖ, DIRBA_NUO from DARBUOTOJAS
-- ORDER BY DIRBA_NUO;
-- SELECT VARDAS, PAVARDĖ, DIRBA_NUO from DARBUOTOJAS
-- ORDER BY DIRBA_NUO DESC;
-- SELECT PROJEKTAS_ID, count(ID) from DARBUOTOJAS
-- GROUP BY PROJEKTAS_ID;
-- SELECT PROJEKTAS_ID, count(ID) as c from DARBUOTOJAS
-- GROUP BY PROJEKTAS_ID
-- HAVING c > 3;
SELECT PROJEKTAS_ID, PAREIGOS, count(PROJEKTAS_ID) as skaicius from DARBUOTOJAS
where pareigos="Programuotojas"
GROUP BY PROJEKTAS_ID;





